package com.easternhealthconnect.test;
import java.util.Date;
import java.util.Calendar;
import java.time.LocalDate;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class DateHelper implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DateHelper() {
    }
    
    public static LocalDate getToday() {
		return LocalDate.now();
	}
	
	public static LocalDate get6MonthsBefore() {
		return LocalDate.now().plusMonths(-6);
	}
	
	public static LocalDate get6MonthsLater() {
        return LocalDate.now().plusMonths(6);
	}

    public static LocalDate addMonths(int monthCount) {
         return LocalDate.now().plusMonths(monthCount);
    }

    public static LocalDate addYears(int yearCount) {
         return LocalDate.now().plusYears(yearCount);
    }

}