package com.easternhealthconnect.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Eligibility implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Is Eligible")
	private java.lang.Boolean isEligible;
	@org.kie.api.definition.type.Label(value = "InEligibility Reasons")
	private java.lang.String inEligibilityReasons;

	public Eligibility() {
	}

	public java.lang.Boolean getIsEligible() {
		return this.isEligible;
	}

	public void setIsEligible(java.lang.Boolean isEligible) {
		this.isEligible = isEligible;
	}

	public java.lang.String getInEligibilityReasons() {
		return this.inEligibilityReasons;
	}

	public void setInEligibilityReasons(java.lang.String inEligibilityReasons) {
		this.inEligibilityReasons = inEligibilityReasons;
	}

	public Eligibility(java.lang.Boolean isEligible,
			java.lang.String inEligibilityReasons) {
		this.isEligible = isEligible;
		this.inEligibilityReasons = inEligibilityReasons;
	}

}