package com.easternhealthconnect.test;

import java.time.LocalDate;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Age")
	private int age;

	@org.kie.api.definition.type.Label("Gender")
	private java.lang.String gender;

	@org.kie.api.definition.type.Label("Implants")
	private java.lang.Boolean implants;

	@org.kie.api.definition.type.Label("MCP Number")
	private java.lang.Long mcp_Number;

	@org.kie.api.definition.type.Label("Current Breast Problem")
	private java.lang.Boolean current_Breast_Problem;

	@org.kie.api.definition.type.Label("Breast Biopsy")
	private String breast_Biopsy;

	@org.kie.api.definition.type.Label("Breast Biopsy Date")
	private LocalDate breast_Biopsy_Date;

	@org.kie.api.definition.type.Label("Mammogram")
	private String mammogram;

	@org.kie.api.definition.type.Label("Mammogram Date")
	private LocalDate mammogram_Date;

	private java.lang.Boolean isEligible;

	@org.kie.api.definition.type.Label("MCP Expiration Date")
	private java.time.LocalDate mcp_Expiration_Date;

	@org.kie.api.definition.type.Label("Mammogram Breast Density")
	private java.lang.Integer mammogram_Breast_Density;

	@org.kie.api.definition.type.Label("Last FIT Result")
	private String last_FIT_Result;

	@org.kie.api.definition.type.Label("Last FIT Result Date")
	private LocalDate last_FIT_result_date;

	@org.kie.api.definition.type.Label("Last Biopsy Date")
	private LocalDate last_biopsy_date;

	@org.kie.api.definition.type.Label("Co- morbidities: Crohn’s, Colitis, Other")
	private Boolean co_morbities;

	@org.kie.api.definition.type.Label("Status")
	private java.lang.String status;

	@org.kie.api.definition.type.Label("ResponseCorrespondence")
	private java.lang.Boolean responseCorrespondence;

	@org.kie.api.definition.type.Label("Last Colonoscopy result")
	private java.lang.String last_Colonoscopy_Result;

	@org.kie.api.definition.type.Label("Last Colonoscopy result date")
	private java.time.LocalDate last_Colonoscopy_Result_Date;

	@org.kie.api.definition.type.Label("Last CT Colonography result")
	private java.lang.String last_CT_Colonography_Result;

	@org.kie.api.definition.type.Label("Last CT Colonography result date")
	private java.time.LocalDate last_CT_Colonography_Result_Date;

	@org.kie.api.definition.type.Label("Ineligibility Reason")
	private java.lang.String reason_For_Ineligibility;

	@org.kie.api.definition.type.Label("Date Of Death")
	private java.time.LocalDate date_Of_Death;

	private java.util.List<java.lang.String> reason_For_Ineligibility_List;

	private java.lang.String eligibility_Program;

	private java.lang.String screening_Program;

	@org.kie.api.definition.type.Label("FDR < 60 Years")
	private java.lang.Boolean fdr_Less_60_Years;

	@org.kie.api.definition.type.Label("Family History of Cancer")
	private java.util.List<java.lang.String> family_History_Of_Cancer;

	@org.kie.api.definition.type.Label("Previous Breast Cancer")
	private java.util.List<java.lang.String> history_Of_Cancer;

	@org.kie.api.definition.type.Label("Last Cytology Result")
	private java.lang.String last_Cytology_Result;

	@org.kie.api.definition.type.Label("Last Cytology Date")
	private java.time.LocalDate last_Cytology_Date;

	@org.kie.api.definition.type.Label("Latest HPV Status")
	private java.lang.String latest_HPV_Status;

	@org.kie.api.definition.type.Label("Current Cancer")
	private java.util.List<java.lang.String> current_Cancer;

	private java.lang.String program_Cohort;

	public Person() {
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public java.lang.Boolean getImplants() {
		return this.implants;
	}

	public void setImplants(java.lang.Boolean implants) {
		this.implants = implants;
	}

	public java.lang.Long getMCP_Number() {
		return this.mcp_Number;
	}

	public void setMCP_Number(java.lang.Long MCP_Number) {
		this.mcp_Number = MCP_Number;
	}

	public java.lang.Boolean getCurrent_Breast_Problem() {
		return this.current_Breast_Problem;
	}

	public void setCurrent_Breast_Problem(
			java.lang.Boolean current_Breast_Problem) {
		this.current_Breast_Problem = current_Breast_Problem;
	}

	public java.lang.Boolean getIsEligible() {
		return this.isEligible;
	}

	public void setIsEligible(java.lang.Boolean isEligible) {
		this.isEligible = isEligible;
	}

	public java.time.LocalDate getBreast_Biopsy_Date() {
		return this.breast_Biopsy_Date;
	}

	public void setBreast_Biopsy_Date(java.time.LocalDate breast_Biopsy_Date) {
		this.breast_Biopsy_Date = breast_Biopsy_Date;
	}

	public java.time.LocalDate getMammogram_Date() {
		return this.mammogram_Date;
	}

	public void setMammogram_Date(java.time.LocalDate mammogram_Date) {
		this.mammogram_Date = mammogram_Date;
	}

	public java.time.LocalDate getMcp_Expiration_Date() {
		return this.mcp_Expiration_Date;
	}

	public void setMcp_Expiration_Date(java.time.LocalDate mcp_Expiration_Date) {
		this.mcp_Expiration_Date = mcp_Expiration_Date;
	}

	public java.lang.Integer getMammogram_Breast_Density() {
		return this.mammogram_Breast_Density;
	}

	public void setMammogram_Breast_Density(
			java.lang.Integer mammogram_Breast_Density) {
		this.mammogram_Breast_Density = mammogram_Breast_Density;
	}

	public String getLast_FIT_Result() {
		return this.last_FIT_Result;
	}

	public void setLast_FIT_Result(String last_FIT_Result) {
		this.last_FIT_Result = last_FIT_Result;
	}

	public LocalDate getLast_FIT_result_date() {
		return this.last_FIT_result_date;
	}

	public void setLast_FIT_result_date(LocalDate last_FIT_result_date) {
		this.last_FIT_result_date = last_FIT_result_date;
	}

	public LocalDate getLast_biopsy_date() {
		return last_biopsy_date;
	}

	public void setLast_biopsy_date(LocalDate last_biopsy_date) {
		this.last_biopsy_date = last_biopsy_date;
	}

	public Boolean getCo_morbities() {
		return co_morbities;
	}

	public void setCo_morbities(Boolean co_morbities) {
		this.co_morbities = co_morbities;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.Boolean getResponseCorrespondence() {
		return this.responseCorrespondence;
	}

	public void setResponseCorrespondence(
			java.lang.Boolean responseCorrespondence) {
		this.responseCorrespondence = responseCorrespondence;
	}

	public java.lang.String getLast_Colonoscopy_Result() {
		return this.last_Colonoscopy_Result;
	}

	public void setLast_Colonoscopy_Result(
			java.lang.String last_Colonoscopy_Result) {
		this.last_Colonoscopy_Result = last_Colonoscopy_Result;
	}

	public java.time.LocalDate getLast_Colonoscopy_Result_Date() {
		return this.last_Colonoscopy_Result_Date;
	}

	public void setLast_Colonoscopy_Result_Date(
			java.time.LocalDate last_Colonoscopy_Result_Date) {
		this.last_Colonoscopy_Result_Date = last_Colonoscopy_Result_Date;
	}

	public java.lang.String getLast_CT_Colonography_Result() {
		return this.last_CT_Colonography_Result;
	}

	public void setLast_CT_Colonography_Result(
			java.lang.String last_CT_Colonography_Result) {
		this.last_CT_Colonography_Result = last_CT_Colonography_Result;
	}

	public java.time.LocalDate getLast_CT_Colonography_Result_Date() {
		return this.last_CT_Colonography_Result_Date;
	}

	public void setLast_CT_Colonography_Result_Date(
			java.time.LocalDate last_CT_Colonography_Result_Date) {
		this.last_CT_Colonography_Result_Date = last_CT_Colonography_Result_Date;
	}

	public java.lang.String getReason_For_Ineligibility() {
		return this.reason_For_Ineligibility;
	}

	public void setReason_For_Ineligibility(
			java.lang.String reason_For_Ineligibility) {
		this.reason_For_Ineligibility = reason_For_Ineligibility;
	}

	public java.time.LocalDate getDate_Of_Death() {
		return this.date_Of_Death;
	}

	public void setDate_Of_Death(java.time.LocalDate date_Of_Death) {
		this.date_Of_Death = date_Of_Death;
	}

	public java.util.List<java.lang.String> getReason_For_Ineligibility_List() {
		return this.reason_For_Ineligibility_List;
	}

	public void setReason_For_Ineligibility_List(
			java.util.List<java.lang.String> reason_For_Ineligibility_List) {
		this.reason_For_Ineligibility_List = reason_For_Ineligibility_List;
	}

	public java.lang.String getEligibility_Program() {
		return this.eligibility_Program;
	}

	public void setEligibility_Program(java.lang.String eligibility_Program) {
		this.eligibility_Program = eligibility_Program;
	}

	public java.lang.String getScreening_Program() {
		return this.screening_Program;
	}

	public void setScreening_Program(java.lang.String screening_Program) {
		this.screening_Program = screening_Program;
	}

	public java.lang.Boolean getFdr_Less_60_Years() {
		return this.fdr_Less_60_Years;
	}

	public void setFdr_Less_60_Years(java.lang.Boolean fdr_Less_60_Years) {
		this.fdr_Less_60_Years = fdr_Less_60_Years;
	}

	public java.util.List<java.lang.String> getFamily_History_Of_Cancer() {
		return this.family_History_Of_Cancer;
	}

	public void setFamily_History_Of_Cancer(
			java.util.List<java.lang.String> family_History_Of_Cancer) {
		this.family_History_Of_Cancer = family_History_Of_Cancer;
	}

	public java.util.List<java.lang.String> getHistory_Of_Cancer() {
		return this.history_Of_Cancer;
	}

	public void setHistory_Of_Cancer(
			java.util.List<java.lang.String> history_Of_Cancer) {
		this.history_Of_Cancer = history_Of_Cancer;
	}

	public java.lang.String getLast_Cytology_Result() {
		return this.last_Cytology_Result;
	}

	public void setLast_Cytology_Result(java.lang.String last_Cytology_Result) {
		this.last_Cytology_Result = last_Cytology_Result;
	}

	public java.time.LocalDate getLast_Cytology_Date() {
		return this.last_Cytology_Date;
	}

	public void setLast_Cytology_Date(java.time.LocalDate last_Cytology_Date) {
		this.last_Cytology_Date = last_Cytology_Date;
	}

	public java.lang.String getLatest_HPV_Status() {
		return this.latest_HPV_Status;
	}

	public void setLatest_HPV_Status(java.lang.String latest_HPV_Status) {
		this.latest_HPV_Status = latest_HPV_Status;
	}

	public java.lang.String getMammogram() {
		return this.mammogram;
	}

	public void setMammogram(java.lang.String mammogram) {
		this.mammogram = mammogram;
	}

	public java.lang.String getBreast_Biopsy() {
		return this.breast_Biopsy;
	}

	public void setBreast_Biopsy(java.lang.String breast_Biopsy) {
		this.breast_Biopsy = breast_Biopsy;
	}

	public java.util.List<java.lang.String> getCurrent_Cancer() {
		return this.current_Cancer;
	}

	public void setCurrent_Cancer(
			java.util.List<java.lang.String> current_Cancer) {
		this.current_Cancer = current_Cancer;
	}

	public java.lang.String getProgram_Cohort() {
		return this.program_Cohort;
	}

	public void setProgram_Cohort(java.lang.String program_Cohort) {
		this.program_Cohort = program_Cohort;
	}

	public Person(int age, java.lang.String gender, java.lang.Boolean implants,
			java.lang.Long mcp_Number,
			java.lang.Boolean current_Breast_Problem,
			java.lang.String breast_Biopsy,
			java.time.LocalDate breast_Biopsy_Date, java.lang.String mammogram,
			java.time.LocalDate mammogram_Date, java.lang.Boolean isEligible,
			java.time.LocalDate mcp_Expiration_Date,
			java.lang.Integer mammogram_Breast_Density,
			java.lang.String last_FIT_Result,
			java.time.LocalDate last_FIT_result_date,
			java.time.LocalDate last_biopsy_date,
			java.lang.Boolean co_morbities, java.lang.String status,
			java.lang.Boolean responseCorrespondence,
			java.lang.String last_Colonoscopy_Result,
			java.time.LocalDate last_Colonoscopy_Result_Date,
			java.lang.String last_CT_Colonography_Result,
			java.time.LocalDate last_CT_Colonography_Result_Date,
			java.lang.String reason_For_Ineligibility,
			java.time.LocalDate date_Of_Death,
			java.util.List<java.lang.String> reason_For_Ineligibility_List,
			java.lang.String eligibility_Program,
			java.lang.String screening_Program,
			java.lang.Boolean fdr_Less_60_Years,
			java.util.List<java.lang.String> family_History_Of_Cancer,
			java.util.List<java.lang.String> history_Of_Cancer,
			java.lang.String last_Cytology_Result,
			java.time.LocalDate last_Cytology_Date,
			java.lang.String latest_HPV_Status,
			java.util.List<java.lang.String> current_Cancer,
			java.lang.String program_Cohort) {
		this.age = age;
		this.gender = gender;
		this.implants = implants;
		this.mcp_Number = mcp_Number;
		this.current_Breast_Problem = current_Breast_Problem;
		this.breast_Biopsy = breast_Biopsy;
		this.breast_Biopsy_Date = breast_Biopsy_Date;
		this.mammogram = mammogram;
		this.mammogram_Date = mammogram_Date;
		this.isEligible = isEligible;
		this.mcp_Expiration_Date = mcp_Expiration_Date;
		this.mammogram_Breast_Density = mammogram_Breast_Density;
		this.last_FIT_Result = last_FIT_Result;
		this.last_FIT_result_date = last_FIT_result_date;
		this.last_biopsy_date = last_biopsy_date;
		this.co_morbities = co_morbities;
		this.status = status;
		this.responseCorrespondence = responseCorrespondence;
		this.last_Colonoscopy_Result = last_Colonoscopy_Result;
		this.last_Colonoscopy_Result_Date = last_Colonoscopy_Result_Date;
		this.last_CT_Colonography_Result = last_CT_Colonography_Result;
		this.last_CT_Colonography_Result_Date = last_CT_Colonography_Result_Date;
		this.reason_For_Ineligibility = reason_For_Ineligibility;
		this.date_Of_Death = date_Of_Death;
		this.reason_For_Ineligibility_List = reason_For_Ineligibility_List;
		this.eligibility_Program = eligibility_Program;
		this.screening_Program = screening_Program;
		this.fdr_Less_60_Years = fdr_Less_60_Years;
		this.family_History_Of_Cancer = family_History_Of_Cancer;
		this.history_Of_Cancer = history_Of_Cancer;
		this.last_Cytology_Result = last_Cytology_Result;
		this.last_Cytology_Date = last_Cytology_Date;
		this.latest_HPV_Status = latest_HPV_Status;
		this.current_Cancer = current_Cancer;
		this.program_Cohort = program_Cohort;
	}
	
	public void addReasonToList(String reason) {
	    if(this.reason_For_Ineligibility_List == null) this.reason_For_Ineligibility_List = new java.util.ArrayList<java.lang.String>();
	    this.reason_For_Ineligibility_List.add(reason);
	}

}